FROM wordpress:php8.2-fpm

WORKDIR /var/www/html

RUN docker-php-ext-install mysqli

# Copy prepared WordPress files (including plugins, themes, mu-plugins)
COPY src/ /var/www/html/

RUN chown -R www-data:www-data /var/www/html
